CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE patients (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    clinic_id integer NOT NULL,
    passport text NOT NULL,
    birthdate timestamp with time zone NOT NULL,
    firstname text NOT NULL,
    lastname text NOT NULL,
    surename text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_patients" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251126105031_CreatePatientsTable', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE patient_analysis (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    patient_id integer NOT NULL,
    patient_file_link text NULL,
    ai_file_link text NULL,
    status integer NOT NULL,
    ai_answer text NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_patient_analysis" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251126110800_AddPatientAnalysisTable', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE complaints (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name_uz text NOT NULL,
    name_ru text NOT NULL,
    name_en text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_complaints" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251205112127_AddComplaintsTable', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE users (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    email text NOT NULL,
    password_hash text NOT NULL,
    password_plain text NULL,
    clinic_id integer NULL,
    status boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE varification_codes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    code text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_varification_codes PRIMARY KEY (id),
    CONSTRAINT fk_varification_codes_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_varification_codes_user_id ON varification_codes (user_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251207063849_CreateUserAndVerificationCode', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE varification_codes ADD email text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251207064708_AddEmailToVerificationCode', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE varification_codes ADD "ClinicId" integer NULL;

ALTER TABLE varification_codes ADD created_at timestamp with time zone NULL;

ALTER TABLE varification_codes ADD updated_at timestamp with time zone NULL;

ALTER TABLE users ADD created_at timestamp with time zone NULL;

ALTER TABLE users ADD updated_at timestamp with time zone NULL;

CREATE TABLE clinic_details (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    clinic_id integer NOT NULL,
    bank_accaunt text NULL,
    mfo text NULL,
    bank_name text NULL,
    inn text NULL,
    license text NULL,
    address text NULL,
    director text NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_clinic_details" PRIMARY KEY (id)
);

CREATE TABLE clinic_phone_numbers (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    phone_number integer NOT NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_clinic_phone_numbers" PRIMARY KEY (id)
);

CREATE TABLE clinics (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    clinic_name text NULL,
    clinic_logo text NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_clinics" PRIMARY KEY (id)
);

CREATE INDEX "IX_varification_codes_ClinicId" ON varification_codes ("ClinicId");

ALTER TABLE varification_codes ADD CONSTRAINT "FK_varification_codes_clinics_ClinicId" FOREIGN KEY ("ClinicId") REFERENCES clinics (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251207094743_AddClinicData', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE varification_codes DROP CONSTRAINT "FK_varification_codes_clinics_ClinicId";

DROP INDEX "IX_varification_codes_ClinicId";

ALTER TABLE varification_codes DROP COLUMN "ClinicId";

ALTER TABLE patients DROP COLUMN clinic_id;

ALTER TABLE patients ADD gender boolean NOT NULL DEFAULT FALSE;

ALTER TABLE patients ADD phone boolean NOT NULL DEFAULT FALSE;

ALTER TABLE clinic_phone_numbers ADD "ClinicId" integer NULL;

CREATE UNIQUE INDEX "IX_users_clinic_id" ON users (clinic_id);

CREATE INDEX "IX_clinic_phone_numbers_ClinicId" ON clinic_phone_numbers ("ClinicId");

CREATE UNIQUE INDEX "IX_clinic_details_clinic_id" ON clinic_details (clinic_id);

ALTER TABLE clinic_details ADD CONSTRAINT "FK_clinic_details_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE;

ALTER TABLE clinic_phone_numbers ADD CONSTRAINT "FK_clinic_phone_numbers_clinics_ClinicId" FOREIGN KEY ("ClinicId") REFERENCES clinics (id);

ALTER TABLE users ADD CONSTRAINT "FK_users_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251214080212_UpdateTableName', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE patients ALTER COLUMN birthdate TYPE date;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251214091636_UpdateBirthdateType', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE patients ALTER COLUMN phone TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251214092646_UpdatePhoneType', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE users ADD username text NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215154224_AddUsernameToUser', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE users ADD position_id integer NULL;

ALTER TABLE users ADD role_id integer NULL;

CREATE TABLE positions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id integer NULL,
    sort integer NULL,
    name_uz text NULL,
    name_ru text NULL,
    name_en text NULL,
    CONSTRAINT "PK_positions" PRIMARY KEY (id)
);

CREATE TABLE roles (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_name_uz text NULL,
    role_name_ru text NULL,
    role_name_en text NULL,
    CONSTRAINT "PK_roles" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215162232_AddDoctors', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE doctor_position (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    doctor_id integer NULL,
    position_id integer NULL,
    CONSTRAINT "PK_doctor_position" PRIMARY KEY (id)
);

CREATE TABLE doctors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    firstname text NOT NULL,
    lastname text NOT NULL,
    surename text NOT NULL,
    gender boolean NOT NULL,
    phone text NOT NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_doctors" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215163424_AddDoctorTable', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE users DROP CONSTRAINT "FK_users_clinics_clinic_id";

DROP INDEX "IX_users_clinic_id";

ALTER TABLE doctors ADD "UserId1" integer NULL;

CREATE INDEX "IX_users_clinic_id" ON users (clinic_id);

CREATE UNIQUE INDEX "IX_doctors_user_id" ON doctors (user_id);

CREATE UNIQUE INDEX "IX_doctors_UserId1" ON doctors ("UserId1");

CREATE INDEX "IX_doctor_position_doctor_id" ON doctor_position (doctor_id);

CREATE INDEX "IX_doctor_position_position_id" ON doctor_position (position_id);

ALTER TABLE doctor_position ADD CONSTRAINT "FK_doctor_position_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id);

ALTER TABLE doctor_position ADD CONSTRAINT "FK_doctor_position_positions_position_id" FOREIGN KEY (position_id) REFERENCES positions (id);

ALTER TABLE doctors ADD CONSTRAINT "FK_doctors_users_UserId1" FOREIGN KEY ("UserId1") REFERENCES users (id);

ALTER TABLE doctors ADD CONSTRAINT "FK_doctors_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE users ADD CONSTRAINT "FK_users_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215171026_AddforeignKeys', '7.0.20');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215180618_FixDoctorUserId', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE users DROP COLUMN position_id;

ALTER TABLE patients ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE patients ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE patient_analysis ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE patient_analysis ALTER COLUMN created_at DROP NOT NULL;

ALTER TABLE complaints ALTER COLUMN updated_at DROP NOT NULL;

ALTER TABLE complaints ALTER COLUMN created_at DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251215193257_FixDatabase', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE doctors ALTER COLUMN surename DROP NOT NULL;

ALTER TABLE doctors ALTER COLUMN phone DROP NOT NULL;

ALTER TABLE doctors ALTER COLUMN lastname DROP NOT NULL;

ALTER TABLE doctors ALTER COLUMN firstname DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251216144904_ChangeUserAndDoctor', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE doctor_position DROP CONSTRAINT "FK_doctor_position_doctors_doctor_id";

ALTER TABLE doctor_position DROP CONSTRAINT "FK_doctor_position_positions_position_id";

UPDATE doctor_position SET position_id = 0 WHERE position_id IS NULL;
ALTER TABLE doctor_position ALTER COLUMN position_id SET NOT NULL;
ALTER TABLE doctor_position ALTER COLUMN position_id SET DEFAULT 0;

UPDATE doctor_position SET doctor_id = 0 WHERE doctor_id IS NULL;
ALTER TABLE doctor_position ALTER COLUMN doctor_id SET NOT NULL;
ALTER TABLE doctor_position ALTER COLUMN doctor_id SET DEFAULT 0;

ALTER TABLE doctor_position ADD CONSTRAINT "FK_doctor_position_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE;

ALTER TABLE doctor_position ADD CONSTRAINT "FK_doctor_position_positions_position_id" FOREIGN KEY (position_id) REFERENCES positions (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251216145850_ChangeDoctorPosition', '7.0.20');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251216150547_ChangeDoctorPosition1', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE roles RENAME COLUMN role_name_uz TO name_uz;

ALTER TABLE roles RENAME COLUMN role_name_ru TO name_ru;

ALTER TABLE roles RENAME COLUMN role_name_en TO name_en;

ALTER TABLE users ALTER COLUMN email DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251216164545_editUserEmail', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE clinic_phone_numbers DROP CONSTRAINT "FK_clinic_phone_numbers_clinics_ClinicId";

ALTER TABLE clinic_phone_numbers RENAME COLUMN "ClinicId" TO clinic_id;

ALTER INDEX "IX_clinic_phone_numbers_ClinicId" RENAME TO "IX_clinic_phone_numbers_clinic_id";

UPDATE users SET role_id = 0 WHERE role_id IS NULL;
ALTER TABLE users ALTER COLUMN role_id SET NOT NULL;
ALTER TABLE users ALTER COLUMN role_id SET DEFAULT 0;

UPDATE clinic_phone_numbers SET clinic_id = 0 WHERE clinic_id IS NULL;
ALTER TABLE clinic_phone_numbers ALTER COLUMN clinic_id SET NOT NULL;
ALTER TABLE clinic_phone_numbers ALTER COLUMN clinic_id SET DEFAULT 0;

CREATE INDEX "IX_users_role_id" ON users (role_id);

ALTER TABLE clinic_phone_numbers ADD CONSTRAINT "FK_clinic_phone_numbers_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE;

ALTER TABLE users ADD CONSTRAINT "FK_users_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251220124534_updatephoneNumbersClinic', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE clinic_phone_numbers ALTER COLUMN phone_number TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251220132928_updatephoneNumbersClinic1', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE users DROP CONSTRAINT "FK_users_clinics_clinic_id";

ALTER TABLE users ADD CONSTRAINT "FK_users_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251221072612_editUsers', '7.0.20');

COMMIT;

START TRANSACTION;

DROP TABLE patients;

CREATE TABLE patcients (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    passport text NOT NULL,
    birthdate date NOT NULL,
    firstname text NOT NULL,
    lastname text NOT NULL,
    surename text NOT NULL,
    gender boolean NOT NULL,
    phone text NOT NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_patcients" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251221103128_EditPatcient', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE ecg_analyses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    created_doctor_id integer NOT NULL,
    patcient_id integer NOT NULL,
    status integer NULL,
    analyse_file_link text NULL,
    generated_file_link text NULL,
    ai_answer_data bytea NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_ecg_analyses" PRIMARY KEY (id)
);

CREATE TABLE ecg_analyse_complaints (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    ecg_analyse_id integer NOT NULL,
    complaint_id integer NOT NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_ecg_analyse_complaints" PRIMARY KEY (id),
    CONSTRAINT "FK_ecg_analyse_complaints_ecg_analyses_ecg_analyse_id" FOREIGN KEY (ecg_analyse_id) REFERENCES ecg_analyses (id) ON DELETE CASCADE
);

CREATE TABLE ecg_analyse_doctors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    ecg_analyse_id integer NOT NULL,
    doctor_id integer NOT NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_ecg_analyse_doctors" PRIMARY KEY (id),
    CONSTRAINT "FK_ecg_analyse_doctors_ecg_analyses_ecg_analyse_id" FOREIGN KEY (ecg_analyse_id) REFERENCES ecg_analyses (id) ON DELETE CASCADE
);

CREATE INDEX "IX_ecg_analyse_complaints_ecg_analyse_id" ON ecg_analyse_complaints (ecg_analyse_id);

CREATE INDEX "IX_ecg_analyse_doctors_ecg_analyse_id" ON ecg_analyse_doctors (ecg_analyse_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251221125856_ECGAnalyse', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE ecg_analyses ALTER COLUMN ai_answer_data TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251221130313_ECGAnalyse1', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE INDEX "IX_ecg_analyse_doctors_doctor_id" ON ecg_analyse_doctors (doctor_id);

CREATE INDEX "IX_ecg_analyse_complaints_complaint_id" ON ecg_analyse_complaints (complaint_id);

ALTER TABLE ecg_analyse_complaints ADD CONSTRAINT "FK_ecg_analyse_complaints_complaints_complaint_id" FOREIGN KEY (complaint_id) REFERENCES complaints (id) ON DELETE CASCADE;

ALTER TABLE ecg_analyse_doctors ADD CONSTRAINT "FK_ecg_analyse_doctors_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251222173918_updateECGAnalyses', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE INDEX "IX_ecg_analyses_created_doctor_id" ON ecg_analyses (created_doctor_id);

CREATE INDEX "IX_ecg_analyses_patcient_id" ON ecg_analyses (patcient_id);

ALTER TABLE ecg_analyses ADD CONSTRAINT "FK_ecg_analyses_doctors_created_doctor_id" FOREIGN KEY (created_doctor_id) REFERENCES doctors (id) ON DELETE CASCADE;

ALTER TABLE ecg_analyses ADD CONSTRAINT "FK_ecg_analyses_patcients_patcient_id" FOREIGN KEY (patcient_id) REFERENCES patcients (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251223152602_updateECGAnalyses1', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE ecg_analyses ADD generated_short_file_link text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251223154201_updateECGAnalyses2', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE medical_diagnoses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    created_doctor_id integer NOT NULL,
    main_doctor_id integer NOT NULL,
    patcient_id integer NOT NULL,
    diagnose_file_link text NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_medical_diagnoses" PRIMARY KEY (id),
    CONSTRAINT "FK_medical_diagnoses_doctors_created_doctor_id" FOREIGN KEY (created_doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_medical_diagnoses_doctors_main_doctor_id" FOREIGN KEY (main_doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_medical_diagnoses_patcients_patcient_id" FOREIGN KEY (patcient_id) REFERENCES patcients (id) ON DELETE CASCADE
);

CREATE INDEX "IX_medical_diagnoses_created_doctor_id" ON medical_diagnoses (created_doctor_id);

CREATE INDEX "IX_medical_diagnoses_main_doctor_id" ON medical_diagnoses (main_doctor_id);

CREATE INDEX "IX_medical_diagnoses_patcient_id" ON medical_diagnoses (patcient_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260113173056_DiagnosesTableCreate', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE complaints ALTER COLUMN name_uz DROP NOT NULL;

ALTER TABLE complaints ALTER COLUMN name_ru DROP NOT NULL;

ALTER TABLE complaints ALTER COLUMN name_en DROP NOT NULL;

CREATE TABLE lab_analyses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    created_doctor_id integer NOT NULL,
    patcient_id integer NOT NULL,
    status integer NULL,
    analyse_file_link text NULL,
    ai_answer_data text NULL,
    hb numeric NULL,
    rbc numeric NULL,
    wbc numeric NULL,
    plt numeric NULL,
    hct numeric NULL,
    mcv numeric NULL,
    mch numeric NULL,
    mchc numeric NULL,
    esr numeric NULL,
    glucose numeric NULL,
    cholesterol numeric NULL,
    alt numeric NULL,
    ast numeric NULL,
    bilirubin_total numeric NULL,
    bilirubin_direct numeric NULL,
    creatinine numeric NULL,
    urea numeric NULL,
    total_protein numeric NULL,
    albumin numeric NULL,
    calcium numeric NULL,
    sodium numeric NULL,
    potassium numeric NULL,
    iron numeric NULL,
    tsh numeric NULL,
    free_t4 numeric NULL,
    insulin numeric NULL,
    urine_volume numeric NULL,
    urine_density numeric NULL,
    urine_ph numeric NULL,
    urine_protein numeric NULL,
    urine_glucose numeric NULL,
    urine_ketones numeric NULL,
    urine_bilirubin numeric NULL,
    urobilinogen numeric NULL,
    urine_rbc integer NULL,
    urine_wbc integer NULL,
    daily_protein numeric NULL,
    daily_creatinine numeric NULL,
    daily_calcium numeric NULL,
    daily_sodium numeric NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_lab_analyses" PRIMARY KEY (id),
    CONSTRAINT "FK_lab_analyses_doctors_created_doctor_id" FOREIGN KEY (created_doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_lab_analyses_patcients_patcient_id" FOREIGN KEY (patcient_id) REFERENCES patcients (id) ON DELETE CASCADE
);

CREATE TABLE lab_big_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name_uz text NULL,
    name_ru text NULL,
    name_en text NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_lab_big_categories" PRIMARY KEY (id)
);

CREATE TABLE lab_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "BigCategoryId" integer NOT NULL,
    name_uz text NULL,
    name_ru text NULL,
    name_en text NULL,
    measure text NULL,
    normal_min_male double precision NULL,
    normal_max_male double precision NULL,
    normal_min_female double precision NULL,
    normal_max_female double precision NULL,
    column_name text NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_lab_categories" PRIMARY KEY (id),
    CONSTRAINT "FK_lab_categories_lab_big_categories_BigCategoryId" FOREIGN KEY ("BigCategoryId") REFERENCES lab_big_categories (id) ON DELETE CASCADE
);

CREATE TABLE lab_analyse_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    lab_analyse_id integer NOT NULL,
    category_id integer NOT NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_lab_analyse_categories" PRIMARY KEY (id),
    CONSTRAINT "FK_lab_analyse_categories_lab_analyses_lab_analyse_id" FOREIGN KEY (lab_analyse_id) REFERENCES lab_analyses (id) ON DELETE CASCADE,
    CONSTRAINT "FK_lab_analyse_categories_lab_categories_category_id" FOREIGN KEY (category_id) REFERENCES lab_categories (id) ON DELETE CASCADE
);

CREATE INDEX "IX_lab_analyse_categories_category_id" ON lab_analyse_categories (category_id);

CREATE INDEX "IX_lab_analyse_categories_lab_analyse_id" ON lab_analyse_categories (lab_analyse_id);

CREATE INDEX "IX_lab_analyses_created_doctor_id" ON lab_analyses (created_doctor_id);

CREATE INDEX "IX_lab_analyses_patcient_id" ON lab_analyses (patcient_id);

CREATE INDEX "IX_lab_categories_BigCategoryId" ON lab_categories ("BigCategoryId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260124072803_LabAnalyse', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE lab_categories DROP CONSTRAINT "FK_lab_categories_lab_big_categories_BigCategoryId";

ALTER TABLE lab_categories RENAME COLUMN "BigCategoryId" TO big_category_id;

ALTER INDEX "IX_lab_categories_BigCategoryId" RENAME TO "IX_lab_categories_big_category_id";

ALTER TABLE lab_categories ADD CONSTRAINT "FK_lab_categories_lab_big_categories_big_category_id" FOREIGN KEY (big_category_id) REFERENCES lab_big_categories (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260124073212_LabAnalyseEdit', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE lab_categories DROP COLUMN column_name;

ALTER TABLE lab_categories DROP COLUMN measure;

ALTER TABLE lab_categories DROP COLUMN normal_max_female;

ALTER TABLE lab_categories DROP COLUMN normal_max_male;

ALTER TABLE lab_categories DROP COLUMN normal_min_female;

ALTER TABLE lab_categories DROP COLUMN normal_min_male;

CREATE TABLE lab_value_types (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name_uz text NULL,
    name_ru text NULL,
    name_en text NULL,
    measure text NULL,
    normal_min_male double precision NULL,
    normal_max_male double precision NULL,
    normal_min_female double precision NULL,
    normal_max_female double precision NULL,
    column_name text NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_lab_value_types" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260124075800_LabAnalyseEdit12', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE lab_analyses ALTER COLUMN urine_wbc TYPE numeric;

ALTER TABLE lab_analyses ALTER COLUMN urine_rbc TYPE numeric;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260124114820_LabAnalyseEdit33', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE patcients ADD district_id integer NULL;

CREATE TABLE regions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name_uz text NOT NULL,
    name_ru text NOT NULL,
    name_en text NOT NULL,
    CONSTRAINT "PK_regions" PRIMARY KEY (id)
);

CREATE TABLE districts (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    region_id integer NOT NULL,
    name_uz text NOT NULL,
    name_ru text NOT NULL,
    name_en text NOT NULL,
    CONSTRAINT "PK_districts" PRIMARY KEY (id),
    CONSTRAINT "FK_districts_regions_region_id" FOREIGN KEY (region_id) REFERENCES regions (id) ON DELETE CASCADE
);

CREATE INDEX "IX_patcients_district_id" ON patcients (district_id);

CREATE INDEX "IX_districts_region_id" ON districts (region_id);

ALTER TABLE patcients ADD CONSTRAINT "FK_patcients_districts_district_id" FOREIGN KEY (district_id) REFERENCES districts (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260127181458_RegionsDistrictsNewNew', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE patcients ADD address text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260127182729_Adress', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE clinic_details ADD district_id integer NULL;

CREATE INDEX "IX_clinic_details_district_id" ON clinic_details (district_id);

ALTER TABLE clinic_details ADD CONSTRAINT "FK_clinic_details_districts_district_id" FOREIGN KEY (district_id) REFERENCES districts (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260127184907_ClinicAddress', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE medical_diagnoses ADD clinic_id integer NULL;

ALTER TABLE lab_analyses ADD clinic_id integer NULL;

ALTER TABLE ecg_analyses ADD clinic_id integer NULL;

CREATE INDEX "IX_medical_diagnoses_clinic_id" ON medical_diagnoses (clinic_id);

CREATE INDEX "IX_lab_analyses_clinic_id" ON lab_analyses (clinic_id);

CREATE INDEX "IX_ecg_analyses_clinic_id" ON ecg_analyses (clinic_id);

ALTER TABLE ecg_analyses ADD CONSTRAINT "FK_ecg_analyses_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id);

ALTER TABLE lab_analyses ADD CONSTRAINT "FK_lab_analyses_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id);

ALTER TABLE medical_diagnoses ADD CONSTRAINT "FK_medical_diagnoses_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260128185011_ClinicIdToAnalyses', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE holter_analyses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    clinic_id integer NULL,
    created_doctor_id integer NOT NULL,
    patcient_id integer NOT NULL,
    main_doctor_id integer NOT NULL,
    status integer NULL,
    analyse_file_link text NULL,
    ai_answer_data text NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_holter_analyses" PRIMARY KEY (id),
    CONSTRAINT "FK_holter_analyses_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id),
    CONSTRAINT "FK_holter_analyses_doctors_created_doctor_id" FOREIGN KEY (created_doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_holter_analyses_doctors_main_doctor_id" FOREIGN KEY (main_doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_holter_analyses_patcients_patcient_id" FOREIGN KEY (patcient_id) REFERENCES patcients (id) ON DELETE CASCADE
);

CREATE TABLE smad_analyses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    clinic_id integer NULL,
    created_doctor_id integer NOT NULL,
    patcient_id integer NOT NULL,
    main_doctor_id integer NOT NULL,
    status integer NULL,
    analyse_file_link text NULL,
    ai_answer_data text NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_smad_analyses" PRIMARY KEY (id),
    CONSTRAINT "FK_smad_analyses_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id),
    CONSTRAINT "FK_smad_analyses_doctors_created_doctor_id" FOREIGN KEY (created_doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_smad_analyses_doctors_main_doctor_id" FOREIGN KEY (main_doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_smad_analyses_patcients_patcient_id" FOREIGN KEY (patcient_id) REFERENCES patcients (id) ON DELETE CASCADE
);

CREATE INDEX "IX_holter_analyses_clinic_id" ON holter_analyses (clinic_id);

CREATE INDEX "IX_holter_analyses_created_doctor_id" ON holter_analyses (created_doctor_id);

CREATE INDEX "IX_holter_analyses_main_doctor_id" ON holter_analyses (main_doctor_id);

CREATE INDEX "IX_holter_analyses_patcient_id" ON holter_analyses (patcient_id);

CREATE INDEX "IX_smad_analyses_clinic_id" ON smad_analyses (clinic_id);

CREATE INDEX "IX_smad_analyses_created_doctor_id" ON smad_analyses (created_doctor_id);

CREATE INDEX "IX_smad_analyses_main_doctor_id" ON smad_analyses (main_doctor_id);

CREATE INDEX "IX_smad_analyses_patcient_id" ON smad_analyses (patcient_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260201075449_AddHolterSmadTables', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE holter_analyse_doctors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    holter_analyse_id integer NOT NULL,
    doctor_id integer NOT NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_holter_analyse_doctors" PRIMARY KEY (id),
    CONSTRAINT "FK_holter_analyse_doctors_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_holter_analyse_doctors_holter_analyses_holter_analyse_id" FOREIGN KEY (holter_analyse_id) REFERENCES holter_analyses (id) ON DELETE CASCADE
);

CREATE TABLE lab_analyse_doctors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    lab_analyse_id integer NOT NULL,
    doctor_id integer NOT NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_lab_analyse_doctors" PRIMARY KEY (id),
    CONSTRAINT "FK_lab_analyse_doctors_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_lab_analyse_doctors_lab_analyses_lab_analyse_id" FOREIGN KEY (lab_analyse_id) REFERENCES lab_analyses (id) ON DELETE CASCADE
);

CREATE TABLE smad_analyse_doctors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    smad_analyse_id integer NOT NULL,
    doctor_id integer NOT NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_smad_analyse_doctors" PRIMARY KEY (id),
    CONSTRAINT "FK_smad_analyse_doctors_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_smad_analyse_doctors_smad_analyses_smad_analyse_id" FOREIGN KEY (smad_analyse_id) REFERENCES smad_analyses (id) ON DELETE CASCADE
);

CREATE INDEX "IX_holter_analyse_doctors_doctor_id" ON holter_analyse_doctors (doctor_id);

CREATE INDEX "IX_holter_analyse_doctors_holter_analyse_id" ON holter_analyse_doctors (holter_analyse_id);

CREATE INDEX "IX_lab_analyse_doctors_doctor_id" ON lab_analyse_doctors (doctor_id);

CREATE INDEX "IX_lab_analyse_doctors_lab_analyse_id" ON lab_analyse_doctors (lab_analyse_id);

CREATE INDEX "IX_smad_analyse_doctors_doctor_id" ON smad_analyse_doctors (doctor_id);

CREATE INDEX "IX_smad_analyse_doctors_smad_analyse_id" ON smad_analyse_doctors (smad_analyse_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260221190547_UpdateAnalyses', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE audit_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NULL,
    username text NULL,
    action text NOT NULL,
    entity_type text NULL,
    entity_id text NULL,
    old_values text NULL,
    new_values text NULL,
    ip_address text NULL,
    user_agent text NULL,
    request_path text NULL,
    http_method text NULL,
    response_status integer NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_audit_logs" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260405173806_AddAuditLogs', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE smad_analyse_doctors ADD is_viewed boolean NOT NULL DEFAULT FALSE;

ALTER TABLE medical_diagnoses ADD is_viewed boolean NOT NULL DEFAULT FALSE;

ALTER TABLE lab_analyse_doctors ADD is_viewed boolean NOT NULL DEFAULT FALSE;

ALTER TABLE holter_analyse_doctors ADD is_viewed boolean NOT NULL DEFAULT FALSE;

ALTER TABLE ecg_analyse_doctors ADD is_viewed boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260406182534_AddIsViewedToAnalyseDoctors', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE parasitology_analyses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    patcient_id integer NOT NULL,
    clinic_id integer NULL,
    created_doctor_id integer NOT NULL,
    file_path text NULL,
    microscopy_method text NULL,
    magnification text NULL,
    egg_count_per_field integer NULL,
    ai_response text NULL,
    analysis_status text NOT NULL,
    jiddiylik_darajasi integer NULL,
    lang text NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_parasitology_analyses" PRIMARY KEY (id),
    CONSTRAINT "FK_parasitology_analyses_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id),
    CONSTRAINT "FK_parasitology_analyses_doctors_created_doctor_id" FOREIGN KEY (created_doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_parasitology_analyses_patcients_patcient_id" FOREIGN KEY (patcient_id) REFERENCES patcients (id) ON DELETE CASCADE
);

CREATE TABLE parasitology_analysis_doctors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    parasitology_analysis_id integer NOT NULL,
    doctor_id integer NOT NULL,
    CONSTRAINT "PK_parasitology_analysis_doctors" PRIMARY KEY (id),
    CONSTRAINT "FK_parasitology_analysis_doctors_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT "FK_parasitology_analysis_doctors_parasitology_analyses_parasit~" FOREIGN KEY (parasitology_analysis_id) REFERENCES parasitology_analyses (id) ON DELETE CASCADE
);

CREATE TABLE parasitology_results (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    parasitology_analysis_id integer NOT NULL,
    helminth_type text NULL,
    helminth_name_uz text NULL,
    helminth_name_ru text NULL,
    helminth_name_en text NULL,
    confidence numeric NULL,
    infection_level text NULL,
    viloyat text NULL,
    tuman text NULL,
    patient_age_group text NULL,
    patient_gender boolean NOT NULL,
    analysis_date date NULL,
    CONSTRAINT "PK_parasitology_results" PRIMARY KEY (id),
    CONSTRAINT "FK_parasitology_results_parasitology_analyses_parasitology_ana~" FOREIGN KEY (parasitology_analysis_id) REFERENCES parasitology_analyses (id) ON DELETE CASCADE
);

CREATE INDEX "IX_parasitology_analyses_clinic_id" ON parasitology_analyses (clinic_id);

CREATE INDEX "IX_parasitology_analyses_created_doctor_id" ON parasitology_analyses (created_doctor_id);

CREATE INDEX "IX_parasitology_analyses_patcient_id" ON parasitology_analyses (patcient_id);

CREATE INDEX "IX_parasitology_analysis_doctors_doctor_id" ON parasitology_analysis_doctors (doctor_id);

CREATE INDEX "IX_parasitology_analysis_doctors_parasitology_analysis_id" ON parasitology_analysis_doctors (parasitology_analysis_id);

CREATE INDEX "IX_parasitology_results_parasitology_analysis_id" ON parasitology_results (parasitology_analysis_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260422184814_AddParasitologyTables', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE analysis_diagnoses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    analysis_type character varying(20) NOT NULL,
    analysis_id integer NOT NULL,
    doctor_id integer NOT NULL,
    diagnosis_text text NOT NULL,
    clinic_id integer NULL,
    created_at timestamp with time zone NULL,
    updated_at timestamp with time zone NULL,
    CONSTRAINT "PK_analysis_diagnoses" PRIMARY KEY (id),
    CONSTRAINT "FK_analysis_diagnoses_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE
);

CREATE INDEX "IX_analysis_diagnoses_analysis_type_analysis_id" ON analysis_diagnoses (analysis_type, analysis_id);

CREATE INDEX "IX_analysis_diagnoses_doctor_id" ON analysis_diagnoses (doctor_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260424060413_AddAnalysisDiagnosis', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE smad_analyses ADD analysis_date timestamp with time zone NULL;

ALTER TABLE parasitology_analysis_doctors ADD created_at timestamp with time zone NULL;

ALTER TABLE parasitology_analysis_doctors ADD is_viewed boolean NOT NULL DEFAULT FALSE;

ALTER TABLE parasitology_analysis_doctors ADD updated_at timestamp with time zone NULL;

ALTER TABLE parasitology_analyses ADD analysis_date timestamp with time zone NULL;

ALTER TABLE lab_analyses ADD analysis_date timestamp with time zone NULL;

ALTER TABLE holter_analyses ADD analysis_date timestamp with time zone NULL;

ALTER TABLE ecg_analyses ADD analysis_date timestamp with time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260424072457_FixedAddAnalysisDate', '7.0.20');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260424072504_AddIsViewedToParasitologyDoctors', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE ecg_analyses ADD document_number text NULL;

ALTER TABLE smad_analyses ADD document_number text NULL;

ALTER TABLE holter_analyses ADD document_number text NULL;

ALTER TABLE lab_analyses ADD document_number text NULL;

ALTER TABLE parasitology_analyses ADD document_number text NULL;

ALTER TABLE clinics ADD is_active boolean NOT NULL DEFAULT FALSE;


                UPDATE ecg_analyses
                SET document_number = 'NMED-EKG-' || LPAD(id::text, 8, '0')
                WHERE document_number IS NULL;
            


                UPDATE smad_analyses
                SET document_number = 'NMED-SMAD-' || LPAD(id::text, 8, '0')
                WHERE document_number IS NULL;
            


                UPDATE holter_analyses
                SET document_number = 'NMED-HOL-' || LPAD(id::text, 8, '0')
                WHERE document_number IS NULL;
            


                UPDATE lab_analyses
                SET document_number = 'NMED-LAB-' || LPAD(id::text, 8, '0')
                WHERE document_number IS NULL;
            


                UPDATE parasitology_analyses
                SET document_number = 'NMED-PARA-' || LPAD(id::text, 8, '0')
                WHERE document_number IS NULL;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260425082143_AddDocumentNumbers', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE video_call_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    room_name text NOT NULL,
    initiator_id integer NOT NULL,
    recipient_id integer NOT NULL,
    clinic_id integer NOT NULL,
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone NULL,
    status text NOT NULL,
    CONSTRAINT "PK_video_call_sessions" PRIMARY KEY (id),
    CONSTRAINT "FK_video_call_sessions_users_initiator_id" FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT "FK_video_call_sessions_users_recipient_id" FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX "IX_video_call_sessions_initiator_id" ON video_call_sessions (initiator_id);

CREATE INDEX "IX_video_call_sessions_recipient_id" ON video_call_sessions (recipient_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260514153410_AddVideoCallSessions', '7.0.20');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260514155349_VideoCall', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE doctors ADD average_rating numeric NOT NULL DEFAULT 0.0;

ALTER TABLE doctors ADD experience_years integer NULL;

ALTER TABLE doctors ADD total_ratings integer NOT NULL DEFAULT 0;

CREATE TABLE clinic_consultants (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    clinic_id integer NOT NULL,
    consultant_doctor_id integer NOT NULL,
    linked_at timestamp with time zone NOT NULL,
    linked_by_consultation_id integer NOT NULL,
    status text NOT NULL,
    total_consultations integer NOT NULL,
    last_consultation_at timestamp with time zone NULL,
    CONSTRAINT "PK_clinic_consultants" PRIMARY KEY (id),
    CONSTRAINT "FK_clinic_consultants_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT "FK_clinic_consultants_doctors_consultant_doctor_id" FOREIGN KEY (consultant_doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT
);

CREATE TABLE consultations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    clinic_id integer NOT NULL,
    consultant_doctor_id integer NOT NULL,
    clinic_consultant_id integer NULL,
    requested_by_admin_id integer NOT NULL,
    patient_id integer NOT NULL,
    is_first_request boolean NOT NULL,
    note text NULL,
    status text NOT NULL,
    rejection_reason text NULL,
    scheduled_at timestamp with time zone NULL,
    livekit_room_name text NULL,
    concluded_at timestamp with time zone NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_consultations" PRIMARY KEY (id),
    CONSTRAINT "FK_consultations_clinic_consultants_clinic_consultant_id" FOREIGN KEY (clinic_consultant_id) REFERENCES clinic_consultants (id),
    CONSTRAINT "FK_consultations_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT "FK_consultations_doctors_consultant_doctor_id" FOREIGN KEY (consultant_doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_consultations_patcients_patient_id" FOREIGN KEY (patient_id) REFERENCES patcients (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_consultations_users_requested_by_admin_id" FOREIGN KEY (requested_by_admin_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE TABLE consultant_ratings (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    consultant_doctor_id integer NOT NULL,
    consultation_id integer NOT NULL,
    clinic_id integer NOT NULL,
    score integer NOT NULL,
    comment text NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_consultant_ratings" PRIMARY KEY (id),
    CONSTRAINT "FK_consultant_ratings_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT "FK_consultant_ratings_consultations_consultation_id" FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE CASCADE,
    CONSTRAINT "FK_consultant_ratings_doctors_consultant_doctor_id" FOREIGN KEY (consultant_doctor_id) REFERENCES doctors (id) ON DELETE CASCADE
);

CREATE TABLE consultation_analyses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    consultation_id integer NOT NULL,
    analysis_type text NOT NULL,
    analysis_id integer NOT NULL,
    shared_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_consultation_analyses" PRIMARY KEY (id),
    CONSTRAINT "FK_consultation_analyses_consultations_consultation_id" FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE CASCADE
);

CREATE TABLE consultation_conclusions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    consultation_id integer NOT NULL,
    diagnosis text NOT NULL,
    recommendations text NOT NULL,
    medications text NULL,
    follow_up_required boolean NOT NULL,
    follow_up_note text NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_consultation_conclusions" PRIMARY KEY (id),
    CONSTRAINT "FK_consultation_conclusions_consultations_consultation_id" FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_clinic_consultants_clinic_id_consultant_doctor_id" ON clinic_consultants (clinic_id, consultant_doctor_id);

CREATE INDEX "IX_clinic_consultants_consultant_doctor_id" ON clinic_consultants (consultant_doctor_id);

CREATE INDEX "IX_consultant_ratings_clinic_id" ON consultant_ratings (clinic_id);

CREATE INDEX "IX_consultant_ratings_consultant_doctor_id" ON consultant_ratings (consultant_doctor_id);

CREATE UNIQUE INDEX "IX_consultant_ratings_consultation_id" ON consultant_ratings (consultation_id);

CREATE INDEX "IX_consultation_analyses_consultation_id" ON consultation_analyses (consultation_id);

CREATE UNIQUE INDEX "IX_consultation_conclusions_consultation_id" ON consultation_conclusions (consultation_id);

CREATE INDEX "IX_consultations_clinic_consultant_id" ON consultations (clinic_consultant_id);

CREATE INDEX "IX_consultations_clinic_id" ON consultations (clinic_id);

CREATE INDEX "IX_consultations_consultant_doctor_id" ON consultations (consultant_doctor_id);

CREATE INDEX "IX_consultations_patient_id" ON consultations (patient_id);

CREATE INDEX "IX_consultations_requested_by_admin_id" ON consultations (requested_by_admin_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260515070606_AddOnlineConsultationTables', '7.0.20');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260515071745_ConsultantTable', '7.0.20');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260515123109_ConsultantTable1', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE consultations ADD COLUMN IF NOT EXISTS is_link_request boolean NOT NULL DEFAULT FALSE;

ALTER TABLE consultations ALTER COLUMN patient_id DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260516091359_AddLinkRequestColumn', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE clinic_consultants DROP COLUMN linked_by_consultation_id;

ALTER TABLE clinic_consultants ADD linked_by_invitation_id integer NULL;

CREATE TABLE consultant_invitations (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    clinic_id integer NOT NULL,
    consultant_doctor_id integer NOT NULL,
    invited_by_admin_id integer NOT NULL,
    note text NULL,
    status text NOT NULL,
    responded_at timestamp with time zone NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_consultant_invitations" PRIMARY KEY (id),
    CONSTRAINT "FK_consultant_invitations_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT "FK_consultant_invitations_doctors_consultant_doctor_id" FOREIGN KEY (consultant_doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_consultant_invitations_users_invited_by_admin_id" FOREIGN KEY (invited_by_admin_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_clinic_consultants_linked_by_invitation_id" ON clinic_consultants (linked_by_invitation_id);

CREATE INDEX "IX_consultant_invitations_clinic_id_consultant_doctor_id_status" ON consultant_invitations (clinic_id, consultant_doctor_id, status);

CREATE INDEX "IX_consultant_invitations_consultant_doctor_id" ON consultant_invitations (consultant_doctor_id);

CREATE INDEX "IX_consultant_invitations_invited_by_admin_id" ON consultant_invitations (invited_by_admin_id);

ALTER TABLE clinic_consultants ADD CONSTRAINT "FK_clinic_consultants_consultant_invitations_linked_by_invitat~" FOREIGN KEY (linked_by_invitation_id) REFERENCES consultant_invitations (id) ON DELETE SET NULL;

INSERT INTO clinic_consultants
    (clinic_id, consultant_doctor_id, linked_at, linked_by_invitation_id, status, total_consultations, last_consultation_at)
SELECT
    c.clinic_id,
    c.consultant_doctor_id,
    MIN(c.created_at) AS linked_at,
    NULL AS linked_by_invitation_id,
    'active' AS status,
    COUNT(*) FILTER (WHERE c.status IN ('accepted', 'scheduled', 'concluded')) AS total_consultations,
    MAX(c.created_at) FILTER (WHERE c.status IN ('accepted', 'scheduled', 'concluded')) AS last_consultation_at
FROM consultations c
WHERE c.status IN ('accepted', 'scheduled', 'concluded')
  AND NOT EXISTS (
      SELECT 1
      FROM clinic_consultants cc
      WHERE cc.clinic_id = c.clinic_id
        AND cc.consultant_doctor_id = c.consultant_doctor_id
  )
GROUP BY c.clinic_id, c.consultant_doctor_id;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260516105122_SeparateConsultantInvitations', '7.0.20');

COMMIT;

START TRANSACTION;

INSERT INTO clinic_consultants
    (clinic_id, consultant_doctor_id, linked_at, linked_by_invitation_id, status, total_consultations, last_consultation_at)
SELECT
    c.clinic_id,
    c.consultant_doctor_id,
    MIN(c.created_at) AS linked_at,
    NULL AS linked_by_invitation_id,
    'active' AS status,
    COUNT(*) FILTER (WHERE c.status IN ('accepted', 'scheduled', 'concluded')) AS total_consultations,
    MAX(c.created_at) FILTER (WHERE c.status IN ('accepted', 'scheduled', 'concluded')) AS last_consultation_at
FROM consultations c
WHERE c.status IN ('accepted', 'scheduled', 'concluded')
  AND NOT EXISTS (
      SELECT 1
      FROM clinic_consultants cc
      WHERE cc.clinic_id = c.clinic_id
        AND cc.consultant_doctor_id = c.consultant_doctor_id
  )
GROUP BY c.clinic_id, c.consultant_doctor_id;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260516111309_BackfillLegacyConsultantLinks', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE consultations ALTER COLUMN patient_id DROP NOT NULL;

ALTER TABLE consultations ADD is_link_request boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260516120000_ConsultationLinkRequest', '7.0.20');

COMMIT;

START TRANSACTION;

DELETE FROM consultation_conclusions;

DELETE FROM consultations;

DELETE FROM clinic_consultants;

DELETE FROM consultant_invitations;

ALTER TABLE clinic_consultants DROP CONSTRAINT "FK_clinic_consultants_consultant_invitations_linked_by_invitat~";

ALTER TABLE clinic_consultants DROP CONSTRAINT "FK_clinic_consultants_doctors_consultant_doctor_id";

ALTER TABLE consultant_invitations DROP CONSTRAINT "FK_consultant_invitations_clinics_clinic_id";

ALTER TABLE consultant_invitations DROP CONSTRAINT "FK_consultant_invitations_doctors_consultant_doctor_id";

ALTER TABLE consultant_invitations DROP CONSTRAINT "FK_consultant_invitations_users_invited_by_admin_id";

ALTER TABLE consultations DROP CONSTRAINT "FK_consultations_clinic_consultants_clinic_consultant_id";

ALTER TABLE consultations DROP CONSTRAINT "FK_consultations_doctors_consultant_doctor_id";

ALTER TABLE consultations DROP CONSTRAINT "FK_consultations_users_requested_by_admin_id";

DROP TABLE consultant_ratings;

DROP INDEX "IX_consultant_invitations_clinic_id_consultant_doctor_id_status";

DROP INDEX "IX_consultant_invitations_consultant_doctor_id";

ALTER TABLE consultations DROP COLUMN concluded_at;

ALTER TABLE consultations DROP COLUMN is_first_request;

ALTER TABLE consultations DROP COLUMN is_link_request;

ALTER TABLE consultations DROP COLUMN note;

ALTER TABLE consultations DROP COLUMN scheduled_at;

ALTER TABLE consultation_conclusions DROP COLUMN follow_up_note;

ALTER TABLE consultation_conclusions DROP COLUMN follow_up_required;

ALTER TABLE consultation_conclusions DROP COLUMN medications;

ALTER TABLE consultant_invitations DROP COLUMN consultant_doctor_id;

ALTER TABLE consultant_invitations DROP COLUMN created_at;

ALTER TABLE clinic_consultants DROP COLUMN last_consultation_at;

ALTER TABLE consultations RENAME COLUMN requested_by_admin_id TO doctor_id;

ALTER TABLE consultations RENAME COLUMN consultant_doctor_id TO created_by_admin_id;

ALTER INDEX "IX_consultations_requested_by_admin_id" RENAME TO "IX_consultations_doctor_id";

ALTER INDEX "IX_consultations_consultant_doctor_id" RENAME TO "IX_consultations_created_by_admin_id";

ALTER TABLE consultation_conclusions RENAME COLUMN recommendations TO treatment;

ALTER TABLE consultant_invitations RENAME COLUMN updated_at TO invited_at;

ALTER TABLE consultant_invitations RENAME COLUMN invited_by_admin_id TO doctor_id;

ALTER INDEX "IX_consultant_invitations_invited_by_admin_id" RENAME TO "IX_consultant_invitations_doctor_id";

ALTER TABLE clinic_consultants RENAME COLUMN linked_by_invitation_id TO invitation_id;

ALTER TABLE clinic_consultants RENAME COLUMN consultant_doctor_id TO doctor_id;

ALTER INDEX "IX_clinic_consultants_linked_by_invitation_id" RENAME TO "IX_clinic_consultants_invitation_id";

ALTER INDEX "IX_clinic_consultants_consultant_doctor_id" RENAME TO "IX_clinic_consultants_doctor_id";

ALTER INDEX "IX_clinic_consultants_clinic_id_consultant_doctor_id" RENAME TO "IX_clinic_consultants_clinic_id_doctor_id";

UPDATE consultations SET patient_id = 0 WHERE patient_id IS NULL;
ALTER TABLE consultations ALTER COLUMN patient_id SET NOT NULL;
ALTER TABLE consultations ALTER COLUMN patient_id SET DEFAULT 0;

UPDATE consultations SET clinic_consultant_id = 0 WHERE clinic_consultant_id IS NULL;
ALTER TABLE consultations ALTER COLUMN clinic_consultant_id SET NOT NULL;
ALTER TABLE consultations ALTER COLUMN clinic_consultant_id SET DEFAULT 0;

ALTER TABLE consultations ADD consultation_date date NOT NULL DEFAULT DATE '-infinity';

ALTER TABLE consultations ADD price_at_creation numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE consultation_conclusions ADD patient_condition text NOT NULL DEFAULT '';

ALTER TABLE consultation_conclusions ADD updated_at timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE consultant_invitations ADD price_per_session numeric(18,2) NOT NULL DEFAULT 0.0;

ALTER TABLE clinic_consultants ADD current_price numeric(18,2) NOT NULL DEFAULT 0.0;

CREATE TABLE consultant_price_history (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    clinic_consultant_id integer NOT NULL,
    old_price numeric(18,2) NOT NULL,
    new_price numeric(18,2) NOT NULL,
    effective_from date NOT NULL,
    changed_at timestamp with time zone NOT NULL,
    changed_by_user_id integer NOT NULL,
    CONSTRAINT "PK_consultant_price_history" PRIMARY KEY (id),
    CONSTRAINT "FK_consultant_price_history_clinic_consultants_clinic_consulta~" FOREIGN KEY (clinic_consultant_id) REFERENCES clinic_consultants (id) ON DELETE CASCADE,
    CONSTRAINT "FK_consultant_price_history_users_changed_by_user_id" FOREIGN KEY (changed_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_consultant_invitations_clinic_id_doctor_id" ON consultant_invitations (clinic_id, doctor_id);

CREATE INDEX "IX_consultant_price_history_changed_by_user_id" ON consultant_price_history (changed_by_user_id);

CREATE INDEX "IX_consultant_price_history_clinic_consultant_id" ON consultant_price_history (clinic_consultant_id);

ALTER TABLE clinic_consultants ADD CONSTRAINT "FK_clinic_consultants_consultant_invitations_invitation_id" FOREIGN KEY (invitation_id) REFERENCES consultant_invitations (id) ON DELETE SET NULL;

ALTER TABLE clinic_consultants ADD CONSTRAINT "FK_clinic_consultants_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT;

ALTER TABLE consultant_invitations ADD CONSTRAINT "FK_consultant_invitations_clinics_clinic_id" FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE RESTRICT;

ALTER TABLE consultant_invitations ADD CONSTRAINT "FK_consultant_invitations_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT;

ALTER TABLE consultations ADD CONSTRAINT "FK_consultations_clinic_consultants_clinic_consultant_id" FOREIGN KEY (clinic_consultant_id) REFERENCES clinic_consultants (id) ON DELETE RESTRICT;

ALTER TABLE consultations ADD CONSTRAINT "FK_consultations_doctors_doctor_id" FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE RESTRICT;

ALTER TABLE consultations ADD CONSTRAINT "FK_consultations_users_created_by_admin_id" FOREIGN KEY (created_by_admin_id) REFERENCES users (id) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260519170331_AddConsultationV2', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE varification_codes ADD phone text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260525090000_AddPhoneToVerificationCodes', '7.0.20');

COMMIT;

START TRANSACTION;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'varification_codes'
          AND column_name = 'email'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'varification_codes'
          AND column_name = 'phone_number'
    ) THEN
        ALTER TABLE varification_codes RENAME COLUMN email TO phone_number;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'varification_codes'
          AND column_name = 'phone_number'
    ) THEN
        ALTER TABLE varification_codes ADD COLUMN phone_number text;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'varification_codes'
          AND column_name = 'phone'
    ) THEN
        UPDATE varification_codes
        SET phone_number = phone
        WHERE phone IS NOT NULL
          AND phone <> ''
          AND (
              phone_number IS NULL
              OR phone_number = ''
              OR phone_number LIKE '%@phone.nmed.local'
          );

        ALTER TABLE varification_codes DROP COLUMN phone;
    END IF;

    UPDATE varification_codes
    SET phone_number = ''
    WHERE phone_number IS NULL;

    ALTER TABLE varification_codes
    ALTER COLUMN phone_number SET NOT NULL;
END
$$;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260525113000_UsePhoneNumberForVerificationCodes', '7.0.20');

COMMIT;

START TRANSACTION;

CREATE TABLE video_conferences (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    room_name text NOT NULL,
    clinic_id integer NOT NULL,
    patient_id integer NOT NULL,
    created_by_admin_id integer NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    started_at timestamp with time zone NULL,
    ended_at timestamp with time zone NULL,
    CONSTRAINT pk_video_conferences PRIMARY KEY (id),
    CONSTRAINT fk_video_conferences_clinics_clinic_id FOREIGN KEY (clinic_id) REFERENCES clinics (id) ON DELETE CASCADE,
    CONSTRAINT fk_video_conferences_patcients_patient_id FOREIGN KEY (patient_id) REFERENCES patcients (id) ON DELETE CASCADE,
    CONSTRAINT fk_video_conferences_users_created_by_admin_id FOREIGN KEY (created_by_admin_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE video_conference_participants (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    video_conference_id integer NOT NULL,
    doctor_id integer NOT NULL,
    invited_at timestamp with time zone NOT NULL,
    joined_at timestamp with time zone NULL,
    status text NOT NULL,
    CONSTRAINT pk_video_conference_participants PRIMARY KEY (id),
    CONSTRAINT fk_video_conference_participants_doctors_doctor_id FOREIGN KEY (doctor_id) REFERENCES doctors (id) ON DELETE CASCADE,
    CONSTRAINT fk_video_conference_participants_video_conferences_video_conference_id FOREIGN KEY (video_conference_id) REFERENCES video_conferences (id) ON DELETE CASCADE
);

CREATE INDEX ix_video_conferences_clinic_id ON video_conferences (clinic_id);

CREATE INDEX ix_video_conferences_created_by_admin_id ON video_conferences (created_by_admin_id);

CREATE INDEX ix_video_conferences_patient_id ON video_conferences (patient_id);

CREATE UNIQUE INDEX ix_video_conferences_room_name ON video_conferences (room_name);

CREATE INDEX ix_video_conference_participants_doctor_id ON video_conference_participants (doctor_id);

CREATE UNIQUE INDEX ix_video_conference_participants_video_conference_id_doctor_id ON video_conference_participants (video_conference_id, doctor_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260525143000_AddVideoConferences', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE video_conferences ADD admin_joined_at timestamp with time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260609151257_AddAdminJoinedAtToVideoConferences', '7.0.20');

COMMIT;

START TRANSACTION;

ALTER TABLE video_conferences ADD admin_left_at timestamp with time zone NULL;

ALTER TABLE video_conference_participants ADD left_at timestamp with time zone NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260611161307_AddVideoConferenceLeaveTracking', '7.0.20');

COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'doctors'
          AND column_name = 'avatar'
    ) THEN
        ALTER TABLE doctors ADD COLUMN avatar text;
    END IF;
END $$;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260614103000_AddAvatarToDoctors', '7.0.20');

COMMIT;

